export const TIME_RANGE_CONFIG = {
  LIVE: {
    label: "LIVE",
    schedule: "RTD",
    back: 2,
    forward: 0,
    useDateRange: false,
    autoRefresh: true,
    scheduleOverrideable: false,
    note: null,
  },
  "1H": {
    label: "1H",
    schedule: "RTD",
    back: 2,
    forward: 0,
    useDateRange: false,
    autoRefresh: false,
    scheduleOverrideable: false,
    note: null,
  },
  "6H": {
    label: "6H",
    schedule: "NRSS",
    back: 12,
    forward: 0,
    useDateRange: false,
    autoRefresh: false,
    scheduleOverrideable: true,
    note: null,
  },
  "24H": {
    label: "24H",
    schedule: "Interim",
    back: 48,
    forward: 0,
    useDateRange: false,
    autoRefresh: false,
    scheduleOverrideable: true,
    note: null,
  },
  "7D": {
    label: "7D",
    schedule: "Final",
    back: null,
    forward: 0,
    useDateRange: true,
    autoRefresh: false,
    scheduleOverrideable: false,
    note: "7-day range uses Final prices only",
  },
  CUSTOM: {
    label: "CUSTOM",
    schedule: "Final",
    back: null,
    forward: 0,
    useDateRange: true,
    autoRefresh: false,
    scheduleOverrideable: false,
    note: "Custom range uses Final prices only",
  },
} as const;

export type TimeRange = keyof typeof TIME_RANGE_CONFIG;
